# Ensure BiocManager is installed for handling Bioconductor packages like limma
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

# Manually ensure the required Bioconductor package is available
# NOTE: Deploying this code will force the Shiny server to install limma via BiocManager.
# Load all required libraries
library(shiny)
library(ggplot2)
library(dplyr)
library(DT)
library(plotly)
library(ggrepel)
library(stats)
#library(limma) # Now installed robustly
library(tidyr)

# --- 1. GLOBAL CONFIGURATION AND DATA LOADING ---
# NOTE: The paths below must be correct relative to your script's execution environment.
#setwd("/tgen_labs/jfryer/kolney/dirty_mice/dirty_mouse_cohousing/scripts/shiny") # Keep or remove based on your environment

# Define the three primary comparisons
projectID <- "CH"
comparisons_list <- c("CH_vs_Bedding", "Bedding_vs_Clean", "CH_vs_Clean")

# Define color scales for DT tables (LogFC and Adjusted P-value)
brks <- seq(-1.6, 1.6, .2)
clrs <- colorRampPalette(c("#6baed6", "white", "red"))(length(brks) + 1) # Blue to Red
brks2 <- seq(0, 0.05, 0.01)
clrs2 <- colorRampPalette(c("green", "lightgreen", "white"))(length(brks2) + 1) # Green for low P-values

# --- Read in Data (FIXED PATHS) ---

# Read metadata
# Assuming metadata is two levels up from the 'scripts/shiny' directory
metadata <- read.delim("metadata.tsv", header = TRUE, sep = "\t", stringsAsFactors = FALSE) 
# Order the groups and samples by group
info_ordered <- metadata %>%
  dplyr::mutate(group = factor(group, levels = c("Clean", "Bedding", "CH"))) %>%
  dplyr::arrange(group)
# Ensure 'sample' is a factor with levels in the desired order (group-wise)
info_ordered$sample <- factor(info_ordered$sample, levels = unique(info_ordered$sample))
metadata <- info_ordered


# Read in DEGs table (full limma results)
# FIX: Restoring the full relative path using projectID
DEGs_raw <- read.delim("DEGs_AllComparisons.txt", stringsAsFactors = FALSE)
# Fixes for data type errors: Remove sex column and ensure numeric columns are correctly typed
DEGs <- DEGs_raw %>%
  mutate(
    # FIX 1: Standardize comparison names (e.g., "CH vs Clean" -> "CH_vs_Clean")
    comparison = gsub(" ", "_", comparison),
    comparison = as.character(comparison),
    gene_name = as.character(gene_name),
    logFC = as.numeric(logFC),
    P.Value = as.numeric(P.Value),
    adj.P.Val = as.numeric(adj.P.Val),
    AveExpr = as.numeric(AveExpr)
  ) %>%
  # Filter out rows where conversion may have resulted in NA
  filter(!is.na(logFC) & !is.na(P.Value) & !is.na(adj.P.Val))


# Read in cpm data (used for box plots)
# FIX: Restoring the full relative path using projectID
cpm_full <- read.delim("filtered_cpm_gene_names.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# Get available gene names for dropdowns
gene_options <- unique(DEGs$gene_name)

# --- 2. UI DEFINITION (User Interface) ---
ui <- fluidPage(
  tags$head(
    tags$style(HTML("
/* Custom styles for a cleaner look */
.container-fluid { padding: 30px; }
.well { background-color: #f7f7f7; border: 1px solid #e3e3e3; border-radius: 8px; padding: 15px; }
/* FIX 2: Set sidebar background to white */
.sidebar-panel { background-color: #ffffff; padding: 20px; border-right: 1px solid #eee; } 
.main-panel { padding: 20px; }
    "))
  ),
  
  titlePanel("DEG analysis among clean, bedding, and cohoused (CH) mice"),
  h5("Data generated by Donna Roscoe & shiny app created by Kimberly Olney, PhD"),
  h5("Lab of Dr. John Fryer at TGen Arizona"),
  tabsetPanel(
    id = "main_tabs",
    
    # --- Volcano Tab (UPDATED) ---
    tabPanel("Volcano Plot",
             sidebarLayout(
               sidebarPanel(
                 class = "sidebar-panel",
                 width = 3,
                 selectInput(
                   "volcano_comparison",
                   "Select Comparison:",
                   choices = comparisons_list
                 ),
                 # Dynamic Gene Name Selector (for highlight)
                 uiOutput("gene_name_selector_volcano"), 
                 hr(),
                 # Removed slider inputs for lfc_threshold and pval_threshold
                 tags$b("Significance threshold:"),
                 tags$ul(
                   tags$li("q-value < 0.05"),
                   tags$li("|Log2FC| > 0.0") # Changed from 0.0 to 0.25 to reflect plot logic
                 )
               ),
               mainPanel(
                 class = "main-panel",
                 width = 9,
                 h3(textOutput("volcano_title")),
                 plotlyOutput(outputId = "volcano", height = "600px")
               )
             )
    ),
    
    # --- DEGs Tab ---
    tabPanel(
      "DEG Tables",
      div(class = "well",
          fluidRow(
            column(width = 3,
                   selectInput(
                     "comparison_filter",
                     "Comparison:",
                     c("All", unique(as.character(DEGs$comparison)))
                   )),
            column(3,
                   selectInput(
                     "gene_name_filter",
                     "Gene Name:",
                     c("All", gene_options)
                   ))
          ),
          # Updated header to reflect displaying all results
          h4("All Differential Expression Results"), 
          DT::dataTableOutput("table")
      ),
      style = "padding: 20px;"
    ),
    
    # --- cpm Tab ---
    tabPanel("cpm Counts",
             div(class = "well",
                 fluidRow(
                   column(
                     width = 3,
                     "Counts Per Million (cpm) Box Plot",
                     selectInput("counts_labels",
                                 "Gene Name:",
                                 choices = gene_options,
                                 selected = "Lcn2")
                   ),
                   column(
                     width = 9,
                     plotlyOutput(outputId = "counts", height = "500px")
                   )
                 )
             )
    )
  )
)

# --- 3. SERVER DEFINITION (Logic) ---
# --- 3. SERVER DEFINITION (Logic) ---
server <- function(input, output, session) {
  
  # Reactive function to pass the globally loaded data
  data_objects <- reactive({
    # The server logic is fine, it relies on the globally loaded DEGs, metadata, and cpm_full
    return(list(
      all_gene_data = DEGs,
      DEGs = DEGs,
      metadata = metadata,
      cpm_full = cpm_full
    ))
  })
  
  # Reactive subset for the Volcano Plot (UPDATED with counts)
  volcano_data <- reactive({
    req(input$volcano_comparison)
    data <- data_objects()$all_gene_data %>% filter(comparison == input$volcano_comparison)
    
    # Fixed cutoffs
    qval_fixed <- 0.05
    lfc_cutoff_fixed <- 0.0
    
    # Calculate fixed expression status
    data_with_status <- data %>%
      mutate(
        # Use adj.P.Val for coloring significance (qval_fixed)
        Expression = case_when(
          adj.P.Val < qval_fixed & logFC > lfc_cutoff_fixed ~ 'Upregulated',
          adj.P.Val < qval_fixed & logFC < -lfc_cutoff_fixed ~ 'Downregulated',
          TRUE ~ 'Not Significant'
        )
      )
    
    # Calculate Counts for Display
    counts <- data_with_status %>%
      group_by(Expression) %>%
      summarise(count = n())
    
    # Extract specific counts
    upregulated_count <- counts$count[counts$Expression == 'Upregulated']
    downregulated_count <- counts$count[counts$Expression == 'Downregulated']
    
    # Return a list containing the data and the counts
    list(
      data = data_with_status,
      upregulated = ifelse(length(upregulated_count) > 0, upregulated_count, 0),
      downregulated = ifelse(length(downregulated_count) > 0, downregulated_count, 0)
    )
  })
  
  # Dynamic Gene Name Selector (Volcano Tab) - Default to Lcn2
  output$gene_name_selector_volcano <- renderUI({
    gene_names <- unique(data_objects()$all_gene_data$gene_name)
    
    selectizeInput(
      "selected_gene_name_volcano",
      "Search/Highlight Gene:",
      choices = c("None" = "None", gene_names),
      selected = "Lcn2", # STARTING POINT: Set default to Lcn2
      options = list(maxOptions = 10, placeholder = 'Search or select a gene')
    )
  })
  
  # Volcano Plot Title (REVERTED to show only comparison name)
  output$volcano_title <- renderText({
    # Correctly substitute "_vs_" with " vs " for display
    paste("Volcano Plot for:", gsub("_vs_", " vs ", input$volcano_comparison))
  })
  
  output$volcano <- renderPlotly({
    # Retrieve data and counts from the reactive list
    volcano_list <- volcano_data()
    data <- volcano_list$data
    up_count <- volcano_list$upregulated
    down_count <- volcano_list$downregulated
    
    req(nrow(data) > 0)
    
    # Fixed parameters
    qval_fixed <- 0.05
    lfc_cutoff_fixed <- 0.0
    
    # Calculate the y-intercept for the adj.P.Val = 0.05 cutoff
    hadjpval <- (-log10(
      max(data$P.Value[data$adj.P.Val < qval_fixed], na.rm=TRUE)
    ))
    
    # Determine plot limits for positioning the text
    max_y <- max(-log10(data$P.Value), na.rm = TRUE)
    max_x <- max(data$logFC, na.rm = TRUE)
    min_x <- min(data$logFC, na.rm = TRUE)
    
    # Create the text for tooltips
    data <- data %>%
      mutate(
        plot_text = paste(
          "Gene:", gene_name,
          "<br>Log2FC:", round(logFC, 3),
          "<br>P.Value:", format.pval(P.Value, digits=4),
          "<br>Adj.P.Val:", format.pval(adj.P.Val, digits=4),
          "<br>Status:", Expression
        ),
        # Flag for highlighting
        is_selected = (gene_name == input$selected_gene_name_volcano)
      )
    
    # Base ggplot
    p <- ggplot(data, aes(x = logFC, y = -log10(P.Value), text = plot_text)) +
      
      # 1. Plot Not Selected points
      geom_point(data = filter(data, !is_selected),
                 aes(color = Expression), size = 1, alpha = 0.6) +
      
      # 2. Add Horizontal and Vertical Lines
      geom_hline(yintercept = hadjpval, colour = "black", linetype = "dashed") +
      geom_vline(xintercept = c(lfc_cutoff_fixed, -lfc_cutoff_fixed),
                 colour = "black", linetype = "dashed") +
      
      # 3. Add Gene Counts Text
      # Upregulated count (Top Right)
      geom_text(x = max_x,
                y = max_y * 0.95,
                label = paste("Up:", up_count),
                color = "red",
                size = 5,
                hjust = 1, vjust = 1) +
      # Downregulated count (Top Left)
      geom_text(x = min_x,
                y = max_y * 0.95,
                label = paste("Down:", down_count),
                color = "blue",
                size = 5,
                hjust = 0, vjust = 1) +
      
      # 4. Plot Selected point (Lcn2 or other)
      {if (input$selected_gene_name_volcano != "None" && any(data$is_selected)) {
        geom_point(data = filter(data, is_selected),
                   color = "black", size = 4, shape = 21, stroke = 1.5, fill = "gold")
      }} +
      
      # 5. Add Gene Label for selected point
      {if (input$selected_gene_name_volcano != "None" && any(data$is_selected)) {
        geom_text_repel(data = filter(data, is_selected),
                        aes(label = gene_name),
                        box.padding = 0.5,
                        point.padding = 0.5,
                        size = 4,
                        color = "black",
                        fontface = "bold.italic")
      }} +
      
      # 6. Aesthetics
      scale_color_manual(values = c("Upregulated" = "red", "Downregulated" = "blue", `Not Significant` = "gray")) +
      theme_minimal() +
      labs(title = paste(gsub("_", " ", input$volcano_comparison)),
           x = "log2 Fold Change",
           y = "-log10(P-Value)") +
      theme(legend.position = "none") +
      # Ensure plot limits encompass all data points, giving room for text
      xlim(min_x - 0.5, max_x + 0.5)
    
    ggplotly(p, tooltip = "text") %>%
      layout(xaxis = list(title = "log2 Fold Change"),
             yaxis = list(title = "-log10(P-Value)"))
  })
  
  # --- DEG Tables Tab Server Logic (Unchanged but relies on fixed data load) ---
  
  filtered_DEGs <- reactive({
    data <- data_objects()$DEGs
    
    if (input$comparison_filter != "All") {
      data <- data[data$comparison == input$comparison_filter,]
    }
    if (input$gene_name_filter != "All") {
      data <- data[data$gene_name == input$gene_name_filter,]
    }
    # Columns selected (t and B removed previously)
    data %>% select(comparison, gene_id, gene_name, logFC, AveExpr, P.Value, adj.P.Val)
  })
  
  # Render Main Table
  output$table <- DT::renderDataTable(
    DT::datatable(
      filtered_DEGs(),
      options = list(pageLength = 5, scrollX = TRUE),
      rownames = FALSE
    ) %>%
      formatStyle('logFC', backgroundColor = styleInterval(brks, clrs)) %>%
      formatStyle('adj.P.Val', backgroundColor = styleInterval(brks2, clrs2)) %>%
      formatRound(columns = c('logFC', 'AveExpr'), digits = 3) %>%
      formatRound(columns = c('P.Value', 'adj.P.Val'), digits = 4)
  )
  
  # --- cpm Counts Tab Server Logic (UPDATED) ---
  
  # Helper function to load cpm data for a specific gene
  load_gene_counts <- function(gene_name, metadata, cpm_full) {
    
    if (!(gene_name %in% cpm_full$gene_name)) {
      return(NULL)
    }
    
    # 1. Extract the row for the specific gene
    gene_row <- cpm_full %>% filter(gene_name == !!gene_name)
    
    # 2. Reshape the data for plotting using pivot_longer from tidyr
    sample_cpm <- gene_row %>%
      # Explicitly exclude the non-cpm metadata columns for pivoting.
      select(-gene_id, -Chr, -width, -gene_name, -gene_type, -type, -GENEID) %>%
      tidyr::pivot_longer(cols = everything(), names_to = "sample", values_to = "cpm") # Column names are the samples
    
    # 3. Merge with metadata (using sample/sample ID)
    data_cpm <- sample_cpm %>%
      left_join(metadata, by = "sample")
    
    # Add gene_name back and ensure required columns are present
    data_cpm$gene_name <- gene_name
    
    return(data_cpm %>% select(sample, cpm, gene_name, group))
  }
  
  # cpm plot function
  output$counts <- renderPlotly({
    req(input$counts_labels)
    gene_name <- input$counts_labels
    
    if (gene_name == "" || is.na(gene_name)) {
      return(NULL)
    }
    
    data_objects_list <- data_objects()
    current_metadata <- data_objects_list$metadata
    current_cpm_full <- data_objects_list$cpm_full
    data_cpm <- load_gene_counts(gene_name, current_metadata, current_cpm_full)
    
    if (is.null(data_cpm) || nrow(data_cpm) == 0) {
      return(plot_ly() %>% layout(title = paste("Gene", gene_name, "not found or has no cpm data")))
    }
    
    # Ensure group and sample are factors in the correct order for consistent plotting
    data_cpm$group <- factor(data_cpm$group , levels = c("Clean", "Bedding", "CH"))
    data_cpm$sample <- factor(data_cpm$sample, levels = unique(data_cpm$sample[order(data_cpm$group)]))
    
    # Define colors for consistency
    custom_colors <- c("Clean" = "skyblue", "Bedding" = "orange", "CH" = "brown")
    
    # --- 1. Box Plot (Plotly) ---
    p_box <- plot_ly(data_cpm,
                     y = ~cpm,
                     x = ~group,
                     text = ~paste("Sample:", sample, "<br>cpm:", round(cpm, 2)),
                     color = ~group,
                     colors = custom_colors,
                     type = "box",
                     boxpoints = "all", # Keep individual points visible
                     jitter = 0.2,
                     marker = list(size = 8),
                     showlegend = FALSE) %>%
      layout(
        title = paste("cpm for Gene:", gene_name, "(Box Plot)"),
        xaxis = list(title = "", showticklabels = FALSE), # Hide x-axis labels
        yaxis = list(title = "Counts Per Million (cpm)", zeroline = FALSE)
      )
    
    # --- 2. Bar Plot (Column Plot) of Individual Samples (Plotly) ---
    # Use the sample factor for x-axis, coloring by group
    p_bar <- plot_ly(data_cpm,
                     x = ~sample,
                     y = ~cpm,
                     type = 'bar',
                     color = ~group,
                     colors = custom_colors,
                     text = ~paste("Sample:", sample, "<br>Group:", group, "<br>cpm:", round(cpm, 2)),
                     hoverinfo = 'text',
                     showlegend = TRUE) %>%
      layout(
        title = "(Individual Sample Values)",
        xaxis = list(title = "Sample", tickangle = 45),
        yaxis = list(title = "Counts Per Million (cpm)", zeroline = TRUE),
        margin = list(b = 100) # Give space for rotated sample names
      )
    
    # --- 3. Combine the two plots vertically using subplot ---
    # Share X-axis (sample names/groups) between the two plots
    # heights defines the relative size of each plot (box plot is typically smaller)
    subplot(p_box, p_bar,
            nrows = 2,
            heights = c(0.4, 0.6),
            shareX = FALSE, # Do NOT share X axis (box plot uses groups, bar plot uses samples)
            titleY = TRUE) %>%
      # Final layout modifications for the combined plot
      layout(
        title = list(text = paste("cpm for Gene:", gene_name)),
        hovermode = "closest"
      )
  })
}

# Run the application
shinyApp(ui = ui, server = server)
# Run the application
shinyApp(ui = ui, server = server)